# docker-compose.yml.tpl — Reference template for the omp-server compose file.
#
# This file is a reference only. The authoritative copy written to the GCP
# instance is generated by startup-script.sh, which inlines the real values
# for AGENT_UID, AGENT_GID, AGENT_MOUNT_DIR, and DOCKER_GID at provision time.
#
# Daemon model:
#   Docker daemon  — runs on the host VM; socket at /var/run/docker.sock
#                    container user reaches it via group_add: [DOCKER_GID]
#   Podman daemon  — per-user socket at /run/user/1000/podman/podman.sock
#                    owned by uid=1000; no extra group needed
#
# Shared filespace:
#   AGENT_MOUNT_DIR is bind-mounted at the same absolute path on both the host
#   and the container. docker/podman -v flags using this path resolve correctly
#   against the host daemon from either side. Path must never use ~.
#
# User:
#   Runs as uid=1000 (jnesbitt) matching the local workstation so file
#   ownership is consistent across host, container, and any spawned containers.

services:
  omp-server:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    container_name: omp-server
    restart: unless-stopped
    privileged: true
    user: "1000:1000"
    group_add:
      - "999"    # docker group GID on Ubuntu 24.04 with Docker CE; confirm with
                 # `getent group docker | cut -d: -f3` on the host if unsure
    ports:
      - "7077:7077"
    volumes:
      - omp-data:/data
      # Docker socket — agents talk to the host Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
      # Podman user socket — owned by uid=1000, no extra group needed
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
      # Shared filespace — same absolute path on host and container
      - ${AGENT_MOUNT_DIR}:${AGENT_MOUNT_DIR}
    environment:
      OMP_SERVER_DATA_DIR: /data
      OMP_SERVER_PKI_DIR: /data/pki
      OMP_SERVER_PORT: "7077"
      OMP_SERVER_URL: ${OMP_SERVER_URL}
      OMP_SERVER_LOG_LEVEL: ${OMP_SERVER_LOG_LEVEL:-info}
      DOCKER_HOST: unix:///var/run/docker.sock
      CONTAINER_HOST: unix:///run/user/1000/podman/podman.sock
      AGENT_MOUNT_DIR: ${AGENT_MOUNT_DIR}
    healthcheck:
      test: ["CMD", "bun", "-e",
        "const r = await fetch('https://localhost:7077/healthz', {tls:{rejectUnauthorized:false}}); if(!r.ok) process.exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  omp-data:
