apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: omp-gsm
spec:
  provider:
    gcpsm:
      projectID: "${GCP_PROJECT}"
      auth:
        workloadIdentity:
          clusterLocation: "${ZONE}"
          clusterName: "${CLUSTER_NAME}"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
