apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: omp-gsm
spec:
  provider:
    gcpsm:
      projectID: "{{ .Values.project }}"
      auth:
        workloadIdentity:
          clusterLocation: "{{ .Values.zone }}"
          clusterName: "{{ .Values.clusterName }}"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
